node {
  stage 'Checkout'
  git 'https://github.com/kazirahiv/jenkins-test'
  
  stage 'ui build'
  def uit = docker.build 'uitestjenkins'
  
  stage 'bubble build'
  def uit = docker.build 'bubble'
  
  stage 'deploy'
  uit.inside {
    sh "chmod +x -R ${env.WORKSPACE}"
	sh './jenkins/scripts/deliver.sh'
	input message: 'Finished using the web site? (Click "Proceed" to continue)'
	sh './jenkins/scripts/kill.sh'
  }
}