node {
  stage 'Checkout'
  git url: 'https://github.com/kazirahiv/jenkins-test'

  stage 'build'
  docker.build('uitestjenkins')
  docker.build('bubble')

  stage 'deploy'
  sh "chmod +x -R ${env.WORKSPACE}"
  sh './jenkins/scripts/deliver.sh'
  input message: 'Finished using the web site? (Click "Proceed" to continue)'
  sh './jenkins/scripts/kill.sh'
}